version: "3.9"

x-logs: &logs
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "10"
      tag: "{{.ImageName}}|{{.Name}}"

services:

  app_python:
    image: johndenkis/simple_python_app_v2:latest
    ports:
      - 5000:5000
    <<: *logs

  app_go:
    image: johndenkis/simple_go_app_v2:latest
    ports:
      - 2222:5000
    <<: *logs

  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    <<: *logs

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-data:/var/lib/promtail/positions
      - ${PWD}/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    <<: *logs

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki:3100
        EOF
        /run.sh
    ports:
      - "3000:3000"
    <<: *logs

volumes:
  promtail-data: {}